### ISSUE TITLE
Rainsensor 

### ISSUE THREAD

**Issue by sirmoon137** [iobroker-community-adapters/ioBroker.rainbird#11] opened 2022-04-25 15:24 UTC
i have the issue the rain sensor is still true but it didn't rain since yesterday. so it look like the sensor data are still not up to date.

**Comment by thebilberry** [comment] 2022-04-25 17:03
I think it's normal and **no issue**. You can set the sensor how quickly it dries off again. As long as it is still damp (wooden plates are swollen), the sensor status is true. Depending on the amount of rain, temperature and humidity, drying can sometimes take several days. This should also be the case, as the plants should not be watered again after a lot of rain.
You can check this state also in der RainBird app. It should be the same as in ioBroker.

**Comment by StrathCole** [comment] 2022-04-25 18:51
That's what I think, too.

**Comment by Feuer-sturm** [comment] 2024-06-06 21:06
@mcm1957 I think you can close this issue as well because it works as designed.

**Closed** 2024-06-06 21:27 UTC
